agent: false

operator:
  enabled: false

cni:
  install: false

hubble:
  enabled: false

  relay:
    enabled: false

  ui:
    # enable Hubble UI
    enabled: true

    standalone:
      # enable Hubble UI standalone deployment
      enabled: true

    # -- hubble-ui ingress configuration.
    ingress:
      enabled: true
      annotations: 
        cert-manager.io/cluster-issuer: letsencrypt-prod
        # external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        # external-dns.alpha.kubernetes.io/hostname: example.com
        # external-dns.alpha.kubernetes.io/ttl: "120" #optional
      # className: ""
      hosts:
        - hubble.see2.club
      labels: {}
      tls:
        - secretName: hubble-ui-cert
          hosts:
            - hubble.see2.club
