# wildcard-cert
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: kube-system
spec:
  secretName: ingress-cert
  commonName: "*.see2.club"
  dnsNames:
    - "*.see2.club"
  issuerRef:
    name: letsencrypt-prod
    # name: letsencrypt-test
    kind: ClusterIssuer